; Set your COMM to the comport the tuner hardware is using
; Simply if its on COM1 then use 1 , COM2 then use 2, and so on.
; Baud Rate is either 57600 or 115200
; Generally if your hardware is firmware 2.4 or higher then use 115200
; If you have an 841 tuner hardware its always 115200
; If no comport is set, it will prompt
; if no baudrate, default is 115200
; If COMPORT COMM set to 0 it will ALWAYS prompt for a comport number. EVERY connection.
; AP = 1 is AsyncPro
; AP = 2 is Tcomport

[COMPORT]
COMM=6
BAUDRATE=115200
AP=1
IP=192.168.2.99
PORT=5000
WB=0
WBCOMM=2

[TUNERHARDWARE]
HARDWARE=1

[PIDGRID]
PRIMARY=D4D0C8
SECONDARY=808080
FONT=ARIAL
FONTSIZE=8
FONTCOLOR=000000

[EXTRA]
SENDVPW=1
SCANBUTTON=VK_F8
PAUSEBUTTON=VK_F1
HEADER1=RACETRACK_
HEADER2=c
AUTOSAVE=1
SAVEPATH=C:
AUTOINC=1
; AUTOSAVE 0=OFF 1=ON
; Refer to http://www.delphibasics.co.uk/RTL.asp?Name=FormatDateTime 
;
;
; MCI CODE THAT HITS
SCANCOMMANDMCI=%KRS
; WHAT VALUE IT HAS TO BE AT OR OVER TO SEND
SCANCOMMANDVALUE=444
; SEND COMMAND 1
SCANCOMMANDSEND1=0B6C10F1AE01000000000000
; SEND COMMAND 2
SCANCOMMANDSEND2=0B6C10F1AE01808000000000
